title: cv dabin florent
email: dabinflorent@gmail.com
description: > 
  CV dabin florent
baseurl: cv-dabin-florent
url: "http://florentdab.github.io
twitter_username: dabinflorent
github_username:  florentdab

# Build settings
markdown: kramdown
